gitlab-ci node version upgrade (#1688)
* gitlab-ci node version upgrade

As said on the doc page itself: In .gitlab-ci.yml file, the node version needs to be updated to Nodejs version > 12.0.0, otherwise the pipeline will fail with error TypeError: line.matchAll is not a function

* Upgrade node version